version: 0.0.{build}

image: Visual Studio 2019

before_build:
  - dotnet restore ".\src\TvMaze.Api.Client.sln"

build_script:
  - dotnet build ".\src\TvMaze.Api.Client.sln"
    
artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: rRjkOlzuS1YV1Zz1m0twYOFL3p5TvjGKx02l2EdVL9twFUiD76tTI7Kjs/l3aK2f
    skip_symbols: false
    artifact: /.*\.nupkg/