version: 0.0.{build}

image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

before_build:
  - dotnet restore ".\src\TvMaze.Api.Client.sln"

build_script:
  - dotnet build ".\src\TvMaze.Api.Client.sln"
  
after_build:
  - dotnet pack .\src\TvMaze.Api.Client\TvMaze.Api.Client.csproj -c Release -o .\artifacts --include-symbols
    
artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: ENJzzbHUfAdAi5+R2DRqZGe25kwBr11/5WcI2vCey8yGChP8rLm0wBTLDOg6U5XH
    skip_symbols: false
    artifact: /.*\.nupkg/
